require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe NutrientsController do

  def mock_nutrient(stubs={})
    @mock_nutrient ||= mock_model(Nutrient, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all nutrients as @nutrients" do
      Nutrient.stub(:all) { [mock_nutrient] }
      get :index
      assigns(:nutrients).should eq([mock_nutrient])
    end
  end

  describe "GET show" do
    it "assigns the requested nutrient as @nutrient" do
      Nutrient.stub(:find).with("37") { mock_nutrient }
      get :show, :id => "37"
      assigns(:nutrient).should be(mock_nutrient)
    end
  end

  describe "GET new" do
    it "assigns a new nutrient as @nutrient" do
      Nutrient.stub(:new) { mock_nutrient }
      get :new
      assigns(:nutrient).should be(mock_nutrient)
    end
  end

  describe "GET edit" do
    it "assigns the requested nutrient as @nutrient" do
      Nutrient.stub(:find).with("37") { mock_nutrient }
      get :edit, :id => "37"
      assigns(:nutrient).should be(mock_nutrient)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created nutrient as @nutrient" do
        Nutrient.stub(:new).with({'these' => 'params'}) { mock_nutrient(:save => true) }
        post :create, :nutrient => {'these' => 'params'}
        assigns(:nutrient).should be(mock_nutrient)
      end

      it "redirects to the created nutrient" do
        Nutrient.stub(:new) { mock_nutrient(:save => true) }
        post :create, :nutrient => {}
        response.should redirect_to(nutrient_url(mock_nutrient))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nutrient as @nutrient" do
        Nutrient.stub(:new).with({'these' => 'params'}) { mock_nutrient(:save => false) }
        post :create, :nutrient => {'these' => 'params'}
        assigns(:nutrient).should be(mock_nutrient)
      end

      it "re-renders the 'new' template" do
        Nutrient.stub(:new) { mock_nutrient(:save => false) }
        post :create, :nutrient => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nutrient" do
        Nutrient.stub(:find).with("37") { mock_nutrient }
        mock_nutrient.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :nutrient => {'these' => 'params'}
      end

      it "assigns the requested nutrient as @nutrient" do
        Nutrient.stub(:find) { mock_nutrient(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:nutrient).should be(mock_nutrient)
      end

      it "redirects to the nutrient" do
        Nutrient.stub(:find) { mock_nutrient(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(nutrient_url(mock_nutrient))
      end
    end

    describe "with invalid params" do
      it "assigns the nutrient as @nutrient" do
        Nutrient.stub(:find) { mock_nutrient(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:nutrient).should be(mock_nutrient)
      end

      it "re-renders the 'edit' template" do
        Nutrient.stub(:find) { mock_nutrient(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nutrient" do
      Nutrient.stub(:find).with("37") { mock_nutrient }
      mock_nutrient.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the nutrients list" do
      Nutrient.stub(:find) { mock_nutrient }
      delete :destroy, :id => "1"
      response.should redirect_to(nutrients_url)
    end
  end

end
